### ISSUE TITLE
Eslint: Add common linter rules for development

### ISSUE THREAD

**Issue by ivanlori** [stormkit-io/app-stormkit-io#11]
Before starting any development I suggest to add global rules for linter, I've seen that there is already .eslintrc but with few rules. Can we add a more consistent rules for the project?

**Comment by svedova** [comment]
Sure! I don't have strong preferences on this but we can use a plugin like: https://github.com/yannickcr/eslint-plugin-react WDYT?

**Comment by ivanlori** [comment]
Great! I will implement that with a reference link in our file :D

**Comment by ivanlori** [comment]
I will add also specific rules that are not reported to that documentation, we can talk about and change them based on our tastes :)
