### ISSUE TITLE
Add build root

### ISSUE THREAD

**Issue by svedova** [stormkit-io/app-stormkit-io#123]
So the thing is as of now we are able to pass a build command and let the application do what it does. What if we have kind of a monorepo or different structure in the git repository - let's say I have a package and I want to deploy its docs (which is an application itself placed inside the `/docs` directory with it's own `package.json`)?

Would be cool to add another input field to the proposal of @imangm to define the "build root" - the location where the build command is being executed.

WDYT?

_Originally posted by @aerophobic in https://github.com/stormkit-io/app-stormkit-io/issues/116#issuecomment-820432061_

**Comment by svedova** [comment]
@aerophobic we are slightly changing the implementation here. 

The initial idea was to add a `build root` input. While the input is a great idea, we want to keep the build configuration as simple as possible. Extending it with new inputs may complicate the build configuration. Therefore, we came up with a different idea 😌 

The idea is to leverage one of our existing features, that is, the environment variables. By using special environment variables `SK_*`, we should be able to configure the deployer. This is a scalable approach, as we can list these variables in a documentation page, and we can add as many as we want without complicating the build configuratrion.

For instance, the `SK_CWD` (current working directory) is exactly introduced for this reason. 

I created an app using the following repository: https://github.com/stormkit-io/stormkit-examples. Each subfolder is actually an application. 

Then I went ahead and created an app for `create-react-app` and provided this build configuration:

<img width="996" alt="Screenshot 2021-11-12 at 20 36 14" src="https://user-images.githubusercontent.com/3321893/141515887-4ca6518b-c92e-4bd3-a8fe-21acfe3bca26.png">

The value of `SK_CWD`, in this case, corresponds to the subfolder. The deployer will `cd` in this directory and perform all operations within this working directory. 

You can then verify that this variable was picked by checking the logs: 

<img width="939" alt="Screenshot 2021-11-12 at 21 27 38" src="https://user-images.githubusercontent.com/3321893/141516890-ceccca2e-9121-4cb8-b087-ae96d296d43a.png">

This feature is currently on the canary environment. Hopefully next week I'm going to merge it. 

Also, in order for monorepos to work properly, I'll also have to work on https://github.com/stormkit-io/app-stormkit-io/issues/213. This feature will allow using the same branch for different environment variables.

I'm going to close this issue as soon as the new deployer service is on production.

**Comment by aerophobic** [comment]
@svedova fanatstic approach to solve the requirements and stay with a clean and easy user interface! I like the way to handle subfolders and can't wait to see this in production 🙏

**Comment by svedova** [comment]
This is now possible with the `SK_CWD` environment variable. I'll update the documentation soon. I'm closing this issue.
