### ISSUE TITLE
Implement the loading spinner for Bitbucket pagination

### ISSUE THREAD

**Issue by svedova** [stormkit-io/app-stormkit-io#14]
**Description**

https://github.com/stormkit-io/app-stormkit-io/pull/13 implements the loading button for bitbucket repositories. When the button is clicked, more repositories are loaded. 

**Problem** 

When the loading button is clicked there is no visual implementation which displays that content is loading. 

**Solution**

The `Button` component has a `loading` property which when set `true` displays a spinner. Using this property, we can display a spinner when content is loading.

**Comment by aerophobic** [comment]
**Loading Spinner**
I solved this issue - you can see a recording [here](https://www.loom.com/share/9578c6c25c2d44a6b60cf35465b62472).

**Improvement**
We want to show the loading spinner to give the user feedback about the pending request. To further improve the user experience I tried an supplementing enhancement which fades in the additionally loaded repositories. You can watch the beheviour [here](https://www.loom.com/share/44c2337f4c5f43a2ae0785065ef07093).

WDYT?

**Comment by svedova** [comment]
WOW that's awesome! I'm in love with it. It's GREAT to have a designer here :)
