### ISSUE TITLE
Refactor: Naming of page directories and components

### ISSUE THREAD

**Issue by aerophobic** [stormkit-io/app-stormkit-io#15]
# Naming for directories and components
### Dynamic Routes
Due to windows lacking the ability of using colons : in file and directory names, it might make sense to change the style of the naming for dynamic pages. Otherwise windows users won't be able to checkout and work with the project (unless through a WSL like Ubuntu / Debian).

### Capitalization
As of now, component names aswell as page names are capitalized. Especially capitalization in directory names might seem unfamiliar and a refactoring according to a new naming convention might make sense.

## Proposal

> While surveying prior art, the most common symbols used to denote a parameter were _, $ and []. (source: [vercel / next.js](https://github.com/vercel/next.js/issues/7607))

Vercel's next.js wraps `[]` around named parameters for their dynamic routing while nuxt.js is using `_` symbol at the beginning of the directory or file name.

It'll make sense to use either `_` or `[]` to indicate named parameters while supporting windows as a platform for developers.

### Naming convention for directory and file names
- A filename or directory name that is wrapped with `[]` would be considered a named parameter
- _OR:_ A filename or directory name that is starting with `_` would be considered a named parameter
- File names for components `should` be capitalized to follow best practices (of other frameworks)
- Directory names `must not` be capitalized to follow best practices (of other frameworks)

Let's discuss this issue here to find a final definition how to handle those cases.

**Comment by svedova** [comment]
Thanks @aerophobic for submitting this issue. 

Given the incompatibility issues with Windows I definitely agree that we should refactor the directory names. To me lowercase folder names and capitalised file names sounds like a good solution. The only we should consider is that path names should match the route definition. So for instance, if we have a route like: 

```
/apps/:id/environments/:env-name
```

The directory path should reflect this. So something like:

```
+ apps
  + _id // or [id]
    + envs
       + _env-name
```

We should also consider that currently we have some subfolders in the routes (like `_components`) which hold files related to that path. As an example you check `src/Apps/_components` folder. If we go with the `_` (lodash) approach, we should also find a way to describe private folders. We can do that using `__` (double-lodash) or another prefix.

**Comment by aerophobic** [comment]
I like your suggestion to work with lodash `_` for named parameters and double lodash `__` for private directories - feels intuitive to me.
Altough you said you would go with lowercase names for directories, would you prefer lowercase or camelcase for _named parameter directories_?
```
apps/_id/envs/_env-name
// or
apps/_id/envs/_envName
```
I'd prefer the latter approach similar to nuxt.js approach when working with lodash `_` ([see here](https://nuxtjs.org/guides/features/file-system-routing/#dynamic-nested-routes)).

**Comment by svedova** [comment]
Oh that's a great reference. Agreed, following conventions may make things easier for other developers as well. So `[]` for named arguments and `_` for private folders.

**Comment by svedova** [comment]
So, I'm going to pick this up.

**Comment by aerophobic** [comment]
I wanted to, but couldn't find time to start yet 😬

**Comment by svedova** [comment]
No worries, then I'm picking this up :)

**Comment by svedova** [comment]
Closing this issue as https://github.com/stormkit-io/app-stormkit-io/pull/39 is merged.
