### ISSUE TITLE
[UX] Add link to opening github issue when there is a problem in new app section

### ISSUE THREAD

**Issue by svedova** [stormkit-io/app-stormkit-io#163]
### Discussed in https://github.com/stormkit-io/app-stormkit-io/discussions/160

<div type='discussions-op-text'>

<sup>Originally posted by **eldemcan** September 26, 2021</sup>
![Screenshot 2021-09-26 at 12 06 37](https://user-images.githubusercontent.com/2489876/134805192-f6d44f5e-9281-4b02-80da-45e28e4975f7.png)
</div>

**Comment by filippofinke** [comment]
I think that this issue has already been addressed.

<img width="685" alt="image" src="https://user-images.githubusercontent.com/37296364/155280356-e0d4123d-2fea-43db-903e-a2b17571f751.png">

**Comment by svedova** [comment]
That's correct, thanks @filippofinke for raising this.
