### ISSUE TITLE
[UX] Add search bar when selecting repository for creating app

### ISSUE THREAD

**Issue by svedova** [stormkit-io/app-stormkit-io#164]
### Discussed in https://github.com/stormkit-io/app-stormkit-io/discussions/161

<div type='discussions-op-text'>

<sup>Originally posted by **eldemcan** September 26, 2021</sup>
I have long list of repositories in my github, I should be able to quickly search in the one that I am looking for in new app section

![image](https://user-images.githubusercontent.com/2489876/134805297-a8a6230b-e074-48fa-ac77-07bf1c940dcf.png)
</div>

**Comment by filippofinke** [comment]
I think that this one is resolved by #299.

**Comment by svedova** [comment]
True! Closing issue.
