### ISSUE TITLE
[Feat] Creating a button for customers to send immedite feedback

### ISSUE THREAD

**Issue by eldemcan** [stormkit-io/app-stormkit-io#193]
### Discussed in https://github.com/stormkit-io/app-stormkit-io/discussions/154

<div type='discussions-op-text'>

<sup>Originally posted by **eldemcan** September 24, 2021</sup>
Creating a button for customers to send immedite feedback . For example microsoft azure has something like this, we can simplify this further

![image](https://user-images.githubusercontent.com/2489876/131856892-15fa3515-9a4a-4288-9f3e-dd1cc5bad5f7.png)

Maybe we can direct them to github issues/disscussions page
</div>

**Comment by svedova** [comment]
This is now ready. We can close this issue: 

<img width="386" alt="image" src="https://user-images.githubusercontent.com/3321893/235310410-318820d7-8c7c-4772-8e5f-4f7f0a8db478.png">
