### ISSUE TITLE
[Feat] Outbound webhook

### ISSUE THREAD

**Issue by svedova** [stormkit-io/app-stormkit-io#198]
<div type='discussions-op-text'>

<sup>Originally posted by **eldemcan** September 24, 2021</sup>
When deployment is done we should send a message to slack or discord channel, we can generalise this with webhook feature. </div>

For reference, here's the rest of the discussion: 

![image](https://user-images.githubusercontent.com/3321893/138302306-7e794e73-ec78-4122-a693-276a45f5da15.png)

**Comment by svedova** [comment]
Additional note: 

We should bear in mind the following use cases:

1. User may want to trigger a webhook after a successful deployment
2. User may want to trigger a webhook after a successful publish
3. User may want to trigger a webhook using `GET`, `POST`, `HEAD` methods
4. User may want to include `Headers` in the outbound call 
5. User may want to limit the trigger based on an environment/branch
6. User may want to add multiple webhooks for the same app

**Comment by svedova** [comment]
I'm going to pick this up. @dolphinxyz I've seen you recently opened a similar issue. Can you please describe exactly your use case to see if the implementation above matches your expectations or not.

**Comment by dolphinxyz** [comment]
Ehy @svedova , I can imagine this feature like this:
![image](https://user-images.githubusercontent.com/30242227/146671158-dc1c1dad-ea17-479a-8bcd-ff231ae4ad66.png)

**Comment by svedova** [comment]
Just an update here: I started working on the backend for this feature. The first batch creates an endpoint to insert outbound webhooks. Currently, the user is allowed to store the following information:

```typescript
interface {
  triggerWhen: "on_deploy" | "on_publish",
  requestUrl: string,
  requestMethod "GET|POST|HEAD",
  requestPayload?: string,
  requestHeaders?: Record<string, string>
}
```

User can add multiple webhooks for an application.

**Comment by svedova** [comment]
Another update: second PR is merged. That PR triggers specified outbound webhooks on publish and on deploy.

**Comment by svedova** [comment]
And another update: third PR is merged which creates an endpoint to delete outbound webhooks. Next one will be an endpoint to list the outbound webhooks, then I'll work on the frontend.

**Comment by svedova** [comment]
The backend is ready. I'm going to start to work on the frontend as a next step.

**Comment by svedova** [comment]
@dolphinxyz this feature is now ready to be used. You can check out the documentation from https://www.stormkit.io/docs/deployments/outbound-webhooks
