### ISSUE TITLE
DomainRow.spec.js test fails

### ISSUE THREAD

**Issue by ivanlori** [stormkit-io/app-stormkit-io#22]
Running `npm run test` we notice that DomainRow.spec.js fails test.
According to @svedova , from now tests will be executed before deployment.

**Comment by svedova** [comment]
Yes I've updated the deployment command to execute tests before building it. So Stormkit will let us know if tests are failing beforehand.

**Comment by svedova** [comment]
Hmm @ivanlori the tests seem to be passing for me. 

Can you please provide more context on what is failing? Here's a screenshot of tests passing:

![image](https://user-images.githubusercontent.com/3321893/93306244-43414800-f808-11ea-8182-11b32339a5d1.png)

**Comment by ivanlori** [comment]
mmh it's weird I got this:
<img width="842" alt="Screenshot 2020-09-16 at 10 26 27" src="https://user-images.githubusercontent.com/7620920/93312210-3c660580-f807-11ea-925a-25937cb692e2.png">

**Comment by ivanlori** [comment]
this test fail: "should display the certificate settings"

**Comment by svedova** [comment]
This test seems to be passing for me. 

Can you please run `npm run test --watchAll` and then hit `q` and then hit `p` and type `DomainRow`. The screenshot doesn't show the error details. I guess it doesn't find the text but that seems weird to me. 

Maybe you can also execute `wrapper.debug()` right before the `expect` statement to see the output of the component.

**Comment by ivanlori** [comment]
<img width="641" alt="Screenshot 2020-09-16 at 11 43 36" src="https://user-images.githubusercontent.com/7620920/93320963-fb272300-f811-11ea-85f5-2f87aab73f9f.png">
<img width="1097" alt="Screenshot 2020-09-16 at 11 43 16" src="https://user-images.githubusercontent.com/7620920/93320976-fd897d00-f811-11ea-80c2-748f2d480a8a.png">

Where could it get that data format?

**Comment by svedova** [comment]
Oh seems like this is a localisation issue. `src/testing/data/mock_domain_response.js` returns the `startDate` and `endDate`. Then in `DomainTLSStatus` component we have this formatter:

```
new Date(cert.startDate * 1000).toLocaleDateString("en-CH", {
  year: "numeric",
  month: "long",
  day: "2-digit",
})
```

I think in your environment it produces a different string (note in the error message it says `June 30, 2020` is expected but the dump shows that it prints `30 June 2020`. So seems to be a localisation issue AFAICT.

**Comment by ivanlori** [comment]
Oh I understand, so if this issue doesn't happen on deployment I can close it

**Comment by svedova** [comment]
Can verify it works there as well: 

![image](https://user-images.githubusercontent.com/3321893/93324052-0da75980-f81e-11ea-875e-265f74eda1f4.png)

**Comment by svedova** [comment]
But perhaps it makes sense to investigate the root of the issue so if someone else stumbles on this it would be nice to have a reference, WDYT? (not a priority though for now)

**Comment by ivanlori** [comment]
Ok, I removed the bug label... and should I keep this issue open or something else?

**Comment by svedova** [comment]
Yup it's perfect like this. Thank you 🙏

**Comment by KevSlashNull** [comment]
@svedova @ivanlori, I just "stumbled" over this issue. :sweat_smile: My system also generated `30 June 2020` instead of `June 30, 2020`. It's weird that the issue occurs, even though `en-CH` is specified as locale. Is that maybe not a [BCP 47](https://www.unicode.org/reports/tr35/tr35.html#BCP_47_Conformance) locale? Or did we (you actually) find a bug in the `toLocaleDateString` method?

Using `en` for the locale fixes the issue for me locally.

| `en-CH` | `en` |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/28510368/97365774-83cfbf00-18a6-11eb-8cd8-d9a09bcd5adc.png) | ![image](https://user-images.githubusercontent.com/28510368/97366365-7c5ce580-18a7-11eb-82a0-12fb7f42ef71.png) |

**Comment by svedova** [comment]
@KevSlashNull you're right. That's not a valid BCP 47 locale. Probably that's why it causes weird issues. Ideally we should rely on the browser settings but as a quick workaround we can probably use a valid BCP 47 locale.

**Comment by svedova** [comment]
I've ended up mocking the date object for tests. In the `setup.js` file we have now a `MockDate` instance (which can be extended as wished) that mocks the `toLocaleDateString` method and returns always `ISO8601` format. I'm going to close this issue as tests are passing on my local and on Stormkit CI, but please feel free to reopen if you see anything wrong.
