### ISSUE TITLE
Remember settings when switching deployment environment

### ISSUE THREAD

**Issue by dolphinxyz** [stormkit-io/app-stormkit-io#221]
When I switch deployment environment (Prod VS Staging) the UI uses the same settings.

It happened in the past that I deployed using the wrong branch or build command.

It would be great to set default settings for each deployment environment.

Thanks!

**Comment by svedova** [comment]
Here's the PR: https://github.com/stormkit-io/app-stormkit-io/pull/224. Will be merged soon.

**Comment by svedova** [comment]
@dolphinxyz this should be fixed now, please re-open the issue if you see any other problem :)

**Comment by dolphinxyz** [comment]
many thanks!
