### ISSUE TITLE
Outbound Webhooks - Add Special variable

### ISSUE THREAD

**Issue by dolphinxyz** [stormkit-io/app-stormkit-io#233]
Dear Team,

in addiction to the excellent special variables available for the outbound webhooks, would it be possible to have also the simple Environment name (production, staging, test..)

In this way I could easily distinguish the environment triggering the webhook without the necessity to include sensitive information such as $SK_DEPLOYMENT_ENDPOINT.

Thanks so much!

**Comment by svedova** [comment]
@dolphinxyz this is now live. You can use the `$SK_ENVIRONMENT` special variable to inject the environment name in your webhook. Here's the documentation, the #discord part includes an example on how to use it: https://www.stormkit.io/docs/deployments/outbound-webhooks

I'm going to close this issue, feel free to reopen if you see a bug 👍
