### ISSUE TITLE
Assign role to the invited friend/collaborator

### ISSUE THREAD

**Issue by ivanlori** [stormkit-io/app-stormkit-io#27]
**Current situation**
<img width="771" alt="Screenshot 2020-09-17 at 09 00 44" src="https://user-images.githubusercontent.com/7620920/93431472-76491180-f8c4-11ea-8662-86068a15715a.png">

we can invite friends but we can't assign role to them.

**The goal**
To have a select box with all available roles such "dev", "tester", "CTO" and so on.

**Why**
it could be useful to make visible or hidden different functionalities based on roles

**Comment by svedova** [comment]
It's possible since a while to create [teams and roles](https://www.stormkit.io/docs/features/teams-and-roles). Thanks for opening this issue but now I guess we can close it :)
