### ISSUE TITLE
[bug] error when selecting no env on the deployment modal

### ISSUE THREAD

**Issue by filippofinke** [stormkit-io/app-stormkit-io#302]
**Describe the bug**
When selecting the default selection on the environments lists it throws multiple "Cannot read properties of undefined" errors.

**To Reproduce**

1. Click deploy now
2. Select an environment
3. Select the default option

**Expected behavior**
Reset the modal asking the user to select a valid environment

**Screenshots**
![image](https://user-images.githubusercontent.com/37296364/155201665-adb3cd14-4571-4423-8805-6d0c4caa24b5.png)

**Comment by svedova** [comment]
Closed by #303
