### ISSUE TITLE
[feat] add support to markdown emojis

### ISSUE THREAD

**Issue by filippofinke** [stormkit-io/app-stormkit-io#304]
**Feature**
Add support to github markdown emojis.

List of emojis: [https://gist.github.com/rxaviers/7360908](https://gist.github.com/rxaviers/7360908)

**Current implementation**
Currently emojis aren't rendered but instead shown as normal text.

![image](https://user-images.githubusercontent.com/37296364/155210895-020ea4b7-1ed3-4494-886f-0b2390168bb7.png)

**Expected result**

![image](https://user-images.githubusercontent.com/37296364/155211013-ba6cb47f-174f-4330-86de-23fc5576cb45.png)

**Comment by svedova** [comment]
@filippofinke is there a library that takes care of this?

**Comment by filippofinke** [comment]
> @filippofinke is there a library that takes care of this?

I don't know yet. I have to research if there is something that fit our case.

**Comment by filippofinke** [comment]
What if we just implement the common ones ([https://gitmoji.dev/](https://gitmoji.dev/)) by mapping the emoji name to the relative font-awesome icon?

This way we don't have to add another icon library.
