### ISSUE TITLE
[feat] add an API key token

### ISSUE THREAD

**Issue by filippofinke** [stormkit-io/app-stormkit-io#309]
**Is your feature request related to a problem? Please describe.**
Currently stormkit does provide a simple cli interface, [stormkit-cli](https://github.com/stormkit-io/stormkit-cli), but in order to access the backend, this program require the user to inspect the web requests of stormkit and get the Bearer token from there.

**Describe the solution you'd like**
An API token that can be generated and revoked from the backend that allows third party programs to interact with stormkit.

**Comment by svedova** [comment]
Thanks @filippofinke. Since this is a backend task, I'm going to add the `backend` label and update this issue accordingly when there is progress.

**Comment by svedova** [comment]
We now have Team-level and Environment-Level API keys. 

<img width="681" alt="image" src="https://github.com/stormkit-io/app-stormkit-io/assets/3321893/9e0ec524-96ce-4517-8a89-ef2bd0aa9ec8">

We can close this issue 👍
