### ISSUE TITLE
Add toolip to environment configuration

### ISSUE THREAD

**Issue by eldemcan** [stormkit-io/app-stormkit-io#319]
Stormkit have tooltips in following module

<img width="658" alt="image" src="https://user-images.githubusercontent.com/2489876/156268683-7210048d-4824-44e6-8551-df51a5b423a6.png">

This module appears when user clicks "Deploy Now"

It would be nice to have same module in following modal as well 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/2489876/156268791-0e43932a-22ba-49ec-a5c6-41aac0291cb3.png">

**Comment by svedova** [comment]
Closing issue, #419 improves this flow.
