### ISSUE TITLE
Status stuck at 503 despite app working fine

### ISSUE THREAD

**Issue by robertocommit** [stormkit-io/app-stormkit-io#332]
**Describe the bug**
Despite my app works perfectly, since a few weeks I see status 503.
It seems the status is stuck and cannot be updated anymore with a new one.
The 503 status appeared a while ago after a failed deployment, and after that, it never disappeard.

**Expected behavior**
It should show 200

**Screenshots**
![image](https://user-images.githubusercontent.com/30242227/159135688-0e9a8e95-45ac-4b5e-8ae4-ee9a32b4cd66.png)

**Comment by svedova** [comment]
@dolphinxyz for some reason CF returns `503` when it is pinged from our servers. Not sure why though 🤷 I'm investigating.

**Comment by svedova** [comment]
@dolphinxyz can this be related? https://community.cloudflare.com/t/community-tip-fixing-error-503-service-unavailable-service-temporarily-unavailable/44438

**Comment by svedova** [comment]
Closing this issue -- it was related to the Cloudflare setup.
