### ISSUE TITLE
Better way to show Account Status and Deployment/Month

### ISSUE THREAD

**Issue by dolphinxyz** [stormkit-io/app-stormkit-io#350]
Hey Team,

I think it makes sense for free accounts to always show a banner at the top of the page reminding to upgrade, as well as showing the number of missing deployments per month.

Moreover, would be great to find this page more easily: https://app.stormkit.io/user/account
It took a while before finding the page to upgrade my account.

Thanks!

**Comment by svedova** [comment]
Thanks for the issue @dolphinxyz! This is the next thing we’re gonna work on!

**Comment by svedova** [comment]
This is now in progress.

**Comment by svedova** [comment]
@dolphinxyz here it is: https://github.com/stormkit-io/app-stormkit-io/pull/352 

Create a usage dashboard. 

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/3321893/163722855-942e76f9-5361-4102-84db-94edd3e675dc.png">

When available, this page also displays an `Upgrade account` button: 

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/3321893/163722932-b7bc25fe-8f66-4cc0-8d5e-e648bab43aca.png">

**Comment by dolphinxyz** [comment]
Thanks so much, it looks great!
