### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by so1ve** [stormkit-io/app-stormkit-io#400]
**Describe the solution you'd like**
It seems stormkit only supports npm and yarn. I want to be able to use pnpm.

**Describe alternatives you've considered**
Support pnpm.

**Comment by svedova** [comment]
Hi @so1ve 👋 Thanks for opening this issue. 

I'm assigning this to myself 👍 

/cc @eldemcan

**Comment by svedova** [comment]
@so1ve I have published a version. It seems to work, can you please double check? 

<img width="996" alt="image" src="https://user-images.githubusercontent.com/3321893/183974123-7caf1215-484d-4aa7-8106-6b9175773b64.png">

I'm closing this issue for now, please feel free to reopen in case you encounter a bug.

**Comment by so1ve** [comment]
Great, now it works! Thanks for your quick reply!
