### ISSUE TITLE
Add light theme switch

### ISSUE THREAD

**Issue by timlmit** [stormkit-io/app-stormkit-io#471]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/23659530/212079348-e28134c8-6668-492c-9e7e-b17f47fdfc71.png">

**Comment by svedova** [comment]
Thanks for submitting this issue! @eldemcan FYI.

**Comment by svedova** [comment]
Better late than never 😅

<img width="310" alt="image" src="https://github.com/user-attachments/assets/7d15c2fe-70cb-46e7-bf16-ee6b098bab79">

You can find it by clicking on **Avatar** > **Theme**
