### ISSUE TITLE
Deploying the "sample-project" leads to 404

### ISSUE THREAD

**Issue by KevSlashNull** [stormkit-io/app-stormkit-io#48]
I deployed the `stormkit-dev/sample-project` on `app.stormkit.io` but I encounter a 404 on the URL that is linked in the environment configuration. I might be doing something wrong but I just clicked on `Deploy Now` and kept the defaults.

## Reproduction Steps

1. Create a new app based on `github/stormkit-dev/sample-project`
1. Deploy with the default options (`production` and `master`)
1. When the deployment has succeeded: click on "details" on the production environment card
1. Click on the URL in the environment configuration
1. Encounter the 404 error

## Screenshots

![image](https://user-images.githubusercontent.com/28510368/97371547-c34fd880-18b1-11eb-9eb4-fe4b5b4cc352.png)

Link to 404 (as in the dashboard): https://weavercactus-wcn2s0.stormkit.dev/

Link to deployment (as in the deployment `Click here to preview`): https://weavercactus-wcn2s0-20650493516805.stormkit.dev/

## Expected Behavior

The URL in the environment config leads to an error 404 page.

## Actual Behavior

The URL in the environment config leads to the latest deployment of this environment.

**Comment by svedova** [comment]
The URL section points always to the latest **published** deployment. What do you think the actual behaviour should be if a user deploys but does not publish a deployment? Shall we display a `nothing-published-yet` kind of message or hide the `URL` until something is published?

**Comment by KevSlashNull** [comment]
@svedova, ah, I got confused there then because I didn’t know that you also need to publish after deploying to the `production` environment, sorry! I think a “nothing published yet” message would be easier for a confused user like me to understand (😂 🙈). Maybe it could show the user a “publish" link or a link to the docs.

**Comment by svedova** [comment]
That totally makes sense. The new version is hosted under https://beta.stormkit.dev (which is this repository). I'll look to create a PR for this in the new version.

**Comment by svedova** [comment]
This is now resolved by the redesign #419: 

<img width="786" alt="image" src="https://user-images.githubusercontent.com/3321893/196403984-4cc0fa81-4f1d-49f4-bf9b-76c3df6c2f5a.png">
