### ISSUE TITLE
free timeless acc for  zero budget community ?

### ISSUE THREAD

**Issue by pflegende** [stormkit-io/app-stormkit-io#496]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. 

We'r a zero budget community of caring relatives ♿ 

I'was a little frustrated when I saw

```
Your free trial expires on July 01, 2023. Upgrade to continue using Stormkit.
```

**Describe the solution you'd like**
Is in roadmap samething like this: a free for ever, may be otherwise limited, account?
 for such like [we](linktr.e/pflegende)

**Describe alternatives you've considered**
we could mot multiply to our probably not relevant for stormkit older and caring, that's certainly not a broken leg.
Understnad it only as an kindly question 
:)

**Additional context**
this affects the account associated with this storm kit account.

CU
:)

**Comment by svedova** [comment]
@pflegende, thanks for opening up this issue, we appreciate your feedback.  

For the sake of the wider audience who visits this issue, we have explained the rationale behind our inability to offer a [free account](https://www.stormkit.io/blog/faq) in our FAQ section. We also sent an email detailing this explanation.

We acknowledge that a one-size-fits-all approach doesn't always suffice when it comes to pricing. Adaptability is key and we are prepared to accommodate flexibility. We can grant you complimentary access to Stormkit under the following conditions:

- Your commitment to providing continuous feedback, as it holds immense significance for us.
- Integration of a link to Stormkit from your website. This could take the form of a non-intrusive banner proclaiming "Powered by Stormkit." such as on [feez.ws](https://feez.ws/). Our aim is to enhance awareness about our platform without imposing on your content.

If these options prove unfeasible, we are open to exploring alternative pricing models that would suit your circumstances. 

Let us know what you think.

**Comment by svedova** [comment]
@pflegende if you're still interested, there is now the option to [self-host](https://www.stormkit.io/docs/welcome/self-hosting) Stormkit on a VPS. The first license is free-of-charge. 

Closing this issue but feel free to re-open if you have any other questions.
