### ISSUE TITLE
Mask environment variables in UI with eye symbol toggle

### ISSUE THREAD

**Issue by robertocommit** [stormkit-io/app-stormkit-io#583]
Implement a feature to hide environment variable values in the user interface using an eye symbol toggle. This will enhance security by preventing accidental leaking of sensitive information during video calls or screen sharing. The feature should allow users to reveal the values when needed.

**Comment by svedova** [comment]
@robertocommit thanks for submitting the issue. https://github.com/stormkit-io/app-stormkit-io/pull/584 should solve this issue. 

I didn't implement the mask for `Modify as a string` functionality. Please feel free to open a new feature for that part as well if you need it 🙏 

Closing this issue 👍
