### ISSUE TITLE
Feature Request: Persistent Volumes for Stormkit

### ISSUE THREAD

**Issue by robertocommit** [stormkit-io/app-stormkit-io#586]
## Is your feature request related to a problem?
Currently, Stormkit does not offer any way to maintain persistent files or data across deployments. Each deployment creates a completely new environment, and there's no built-in method to keep any files or data persistent. This limitation makes it challenging for applications that need to maintain state or store data that should persist between updates.

## Describe the solution you'd like
Implement a "volumes" feature in Stormkit that allows users to create small persistent storage spaces (e.g., a few MB or GB) that are not affected by deployments. These volumes would be accessible by the applications and could store various file types such as databases (e.g., SQLite files), images, CSV files, and JSON files.

## Key features
- Ability to create and manage persistent volumes through the Stormkit interface
- Persistence of data across multiple deployments
- Access to these volumes from within the deployed applications
- API for managing files in the volumes, allowing programmatic access and manipulation of stored data

## Describe alternatives you've considered
Currently, there are no built-in alternatives in Stormkit for maintaining persistent data. Users must resort to external database solutions or file storage services, which adds complexity and potential costs to projects that could otherwise benefit from Stormkit's simplicity.

## Additional context
The feature could be integrated into the existing Stormkit interface, possibly under a new "Volumes" section where users can create, manage, and assign persistent storage to their projects. This would allow for storing SQLite databases, configuration files, user-uploaded content, and other data that needs to persist across deployments. The addition of an API for managing files in the volumes would provide developers with powerful programmatic control over their persistent data, enabling more complex workflows and integrations. This could open up possibilities for automated backups, content synchronization, and dynamic content management directly within the Stormkit ecosystem.

**Comment by svedova** [comment]
@robertocommit thanks a lot for the detailed issue description. This feature request makes a lot sense, I'll see what I can do.
