### ISSUE TITLE
Allow Internal API URLs in Trigger Functions

### ISSUE THREAD

**Issue by robertocommit** [stormkit-io/app-stormkit-io#594]
![Screenshot 2024-12-12 at 16 11 13](https://github.com/user-attachments/assets/209fb876-0828-4047-946b-754d93671826)

**Is your feature request related to a problem? Please describe.**
Currently, the trigger function URL field appears to only accept external URLs. This limitation prevents users from referencing internal APIs built within modern web frameworks like Next.js or SvelteKit.

**Describe the solution you'd like**
Add support for internal API paths in the URL field of trigger functions. This would allow:
- Using relative paths (e.g., `/api-path/trigger-endpoint`)
- Supporting internal API routes created within the same application
- Maintaining compatibility with existing external URL support

**Describe alternatives you've considered**
- Creating a separate configuration for internal vs external endpoints
- Setting up environment-specific URL prefixes

The current limitation requires developers to either expose their internal APIs externally or implement workarounds, which could potentially introduce security risks or unnecessary complexity.

**Comment by svedova** [comment]
Thanks @robertocommit 👍 Started working on it.

**Comment by svedova** [comment]
@robertocommit while at it I improved the Triggers page as well and added a new page to view last 25 trigger (including logs). Here's a demo:

[trigger-logs.webm](https://github.com/user-attachments/assets/9fe6a87f-b6cf-43df-917c-5d55ddab3602)

Closing this issue 🙏
