### ISSUE TITLE
Migration of the project to Typescript

### ISSUE THREAD

**Issue by ivanlori** [stormkit-io/app-stormkit-io#8]
**What is it?**
Typescript is a strongly typed, object oriented, compiled language. All TypeScript code is converted into its JavaScript equivalent for the purpose of execution. To use typescript you only need to know Javascript.

**Why?**
- It allows to catch bug early during the development process;
- It is easier to refactor code without breaking it significantly;

**How to implement?**
There will be a tsconfig.json file that handles all settings of the typescript compiler, then all files in .jsx and .js, will be converted to .tsx and .ts. With webpack it is needed a specific loader for typescript.

In the long run will be beneficial for the project.

**Comment by svedova** [comment]
Awesome, thanks a lot for this @ivanlori. 

I'd suggest to move in small batches. Perhaps, one PR can be adding the `.tsconfig` and then slowly we can start the migration process. @ivanlori would you be willing to create an implementation plan since this issue seems to be a bigger one? Something like:

- [ ] Create the typescript config
- [ ] Migrate the App.js 
- [ ] Migrate pages/Apps 
- [ ] ...

**Comment by ivanlori** [comment]
Yes, I can.
I'll start with the following steps:

- [ ] Creation .tsconfig
- [ ] Migration of single component folder
- [ ] Migration of single layout folder
- [ ] Migration of single page folder
- [ ] Migration of single API folder

The big ones is here, how do you prefer, do I open branches for every single steps or just in one bigger branch?

**Comment by svedova** [comment]
I would suggest keeping smaller branches as it becomes easier maintaining and reviewing them. WDYT?

**Comment by ivanlori** [comment]
Sure, for me it's ok 🙂

**Comment by svedova** [comment]
@ivanlori I'm going to check your to-do list for you :) With https://github.com/stormkit-io/app-stormkit-io/pull/96 we have migrated all files in components subfolder to typescript. GREAT JOB man!

**Comment by ivanlori** [comment]
Great! We can move on the next folder! 💯

**Comment by svedova** [comment]
Thanks a lot for driving this @ivanlori 🙏 We now have full support for Typescript and I'm loving it 🙏
